generate_gitlab-cis:
  stage: build
  image:
    name: bitnami/jsonnet:latest
    entrypoint: [""]
  script:
    - jsonnet -m . --ext-str exercism_projects="$(ls -d */)" --ext-str lang="erlang" ".erlang-gitlab-ci-template.jsonnet"
  artifacts:
    paths:
      - .generated-config.yml
      - .erlang-*-gitlab-ci.yml

trigger-tests:
  stage: test
  needs:
    - generate_gitlab-cis
  trigger:
    include:
      - artifact:
          paths:
            - .generated-config.yml
            - .erlang-*-gitlab-ci.yml
        job: generate_gitlab-cis
    strategy: depend
